spring.data.mongodb.uri: ${MONGOCLUSTER_URI:mongodb://localhost/ludoMemoria?retryWrites=true&w=majority}

server.port: ${PORT:8080}

secret: ${SECRET:DEV_SECRET}

spring.mvc.pathmatch.matching-strategy: ant_path_matcher